# © 2022 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.  
# This AWS Content is provided subject to the terms of the AWS Customer Agreement available at  
# http://aws.amazon.com/agreement or other written agreement between Customer and either
# Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

# see more details here: https://pre-commit.com/
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        stages: [ pre-commit ]
        name: Autoflake
        entry: pipenv run autoflake -r .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        stages: [ pre-commit ]
        name: Black
        entry: pipenv run black ./src
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        stages: [ pre-commit, manual ]
        name: Flake8
        entry: pipenv run flake8 --select C ./src
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        stages: [ pre-commit ]
        name: pytest
        entry: pipenv run pytest ./src/app/tests
        pass_filenames: false
        language: system
