version: '3.8'

services:
  spider_backend:
    container_name: spider_backend
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080

    volumes:
      - "./src/:/app"
      - "./data/:/app/data"

    ports:
      - "8080:8080"
