version: '3.8'

services:
  spider_backend:
    container_name: spider_backend
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080

    volumes:
      - "./src/:/app"
      - "./data/:/app/data"
      - "./logs/:/app/logs"

    ports:
      - "8080:8080"

    environment:
      - PYTHONPATH=/app:$PYTHONPATH 
      - LODGERIN_API=/app:$LODGERIN_API 
      - LODGERIN_API_KEY=/app:$LODGERIN_API_KEY 