version: '3.8'

services:
  spider_backend:
    container_name: spider_backend
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080

    volumes:
      - "./src/:/app"
      - "./data/:/app/data"
      - "./logs/:/app/logs"

    ports:
      - "8080:8080"

    environment:
      - PYTHONPATH=/app:$PYTHONPATH
      - LOGS=/app/logs
      - DATA=/app/data
      - LODGERIN_API=${LODGERIN_API:-http://example.com/api}
      - LODGERIN_INTERNAL=${LODGERIN_INTERNAL:-http://internal.example.com}
      - LODGERIN_MAPS_INTERNAL=${LODGERIN_MAPS_INTERNAL:-http://maps.internal.example.com}
      - TOKEN_API_INTERNAL=${TOKEN_API_INTERNAL:-your_secure_token_here}
      - USERNAME_NAFSA=${USERNAME_NAFSA:-default_username_nafsa_token}
      - PASSWORD_NAFSA=${PASSWORD_NAFSA:-default_password_nafsa_token}
      - EMAIL_FLIPCOLIVING=${EMAIL_FLIPCOLIVING:-flipcoliving@example.com}
      - EMAIL_SOMOSATHENEA=${EMAIL_SOMOSATHENEA:-somosathenea@example.com}
      - EMAIL_MAPPING_YUGO=${EMAIL_MAPPING_YUGO:-mapping_yugo.json}
      - EMAIL_YUGO_DEFAULT=${EMAIL_YUGO_DEFAULT:-default_yugo@example.com}
      - EMAIL_VITASTUDENTS=${EMAIL_VITASTUDENTS:-default_vitastudents@example.com}
      - EMAIL_NODIS=${EMAIL_NODIS:-default_nodis@example.com}